___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

### Create an array of 10 zeros 

In [4]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
fives = np.array([5,5,5,5,5,5,5,5,5,5])
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [9]:
one_to_hundred = np.arange(10,51)
one_to_hundred

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
one_to_hundred_even = np.arange(10,51,2)
one_to_hundred_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
matrix_identity = np.ones(9).reshape(3,3)
matrix_identity

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
random_number = np.random.rand()
random_number

0.09575128716427139

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [45]:
random_25 = np.random.randint(0,51,25).reshape(5,5)
random_25

array([[47, 12,  3, 27, 21],
       [36, 46,  2, 32, 46],
       [19, 38, 17, 50, 23],
       [16, 28,  0, 11, 36],
       [30, 47, 10, 48, 23]])

#### Create the following matrix:

In [47]:
random_matrix_go = np.random.randint(0,101,27).reshape(3,3,3)
random_matrix_go

array([[[95, 10, 98],
        [79, 29, 83],
        [74, 87, 61]],

       [[77,  1, 61],
        [73, 85, 39],
        [21, 57, 11]],

       [[35, 34,  9],
        [53, 52, 96],
        [ 7, 97, 20]]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [48]:
lin_space_mat = np.linspace(0,1,20)
lin_space_mat

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [49]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
mat[3][4]

20

20

In [37]:
mat[0:5,1].reshape(5,1)

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [40]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [42]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])